* Distribution of densities in H II regions
+ Collaboration with Eduardo to see how the high-density tail of the ionized density distribution in H II regions might be affecting line ratio density diagnostics
+ 


** Log of advances

*** Advances early January 2025

**** Marimo notebook where I calculate PDFs of simulations
- [[file:explore_sac_cubes.py]]
- This includes the PDF of the density and the ionization parameter
- There is a slight negative correlation between these, but much less than one might think

*** Advances Tue/Wed 11/12 November

**** Notebook where I calculate the DED of a globule flow
- [[file:density_pdf_explore.ipynb]]
- I have an analytic solution for this in the constant velocity and Dyson-law cases
  - [ ] At the moment, I am calculating \(d \ln U / d \ln R\) numerically, but I should be able to find a fully analytic form from what Roberto and I were calculating at the beginning of his maestría project
**** Handwritten notes on density PDF from photoevaporation flow
- [[file:handwritten-notes-density-distribution-2025-11-12.pdf]]
- I do the constant velocity wind case analytically
- I construct the distribution function \(n H_n\), where H_n is the emissivity-weighted histogram of density values 
  - This is the analogue of the SED: \(\nu F_\nu\)
  - I call it the Density Energy Distribution (DED)
** We will use the Orion Nebula as a benchmark
+ Estimate the full density PDF from a combination of empirical and modeling techniques
*** High density tail will come from proplyds
**** Generate a single-proplyd PDF
- based on N(r, \theta) laws from Dyson models
- With scale factors (n_0, r_0), the peak density and i-front radius
**** Integrate over known distributions of proplyd parameters
+ Size distribution from Henney & Arthur, or Vicente (although those are overestimates) or Tsamis:2013a or one of the more recent papers like Ballering:2023a or Boyden:2025a
  + Boyden find r_0 \approx (12 AU) 10**{R / 0.05 pc} which is bizarre
  + This means that the solid angle increases with R, which gives an increased influence of the further proplyds
  + But this cannot carry on forever. They only fit it over range 0 to 0.06 pc (30 arcsec), for which their largest radius is 100 AU
    + So at that point, r/R ~ 0.01, so \theta ~ 0.01 rad = 0.6 deg
    + \Omega / 4 pi = 0.5 (1 - cos(0.6 deg)) = \theta^2 / 4 = 2.5e-5
    + So even with 200 proplyds, we only get a total of 5e-3, so 0.5% of the total emission measure. /And that is probably an overestimate/
  + Vicente:2005a is bad for the close-in disks, but should be better for the further out ones. The chord diameter maxes out at about 1 arcsec for R > 100 arcsec (0.2 pc), which corresponds to radius of about 200 AU
+ Peak density distribution from same sources, or just use the theoretical value (note that Boyden densities are wrong)
+ Spatial proplyd distribution can come directly from catalogs like Ricci:2008a
  + Or we can use the fits from Henney & Arthur, although these are only validated over the inner part
*** Medium densities from globule/filament flows
+ This could be treated in a similar way
+ But we need to account for the finite cavity size (if globules are near Stromgren radius)
** Contribution of turbulence to the PDF
- We could assume it is log-normal
- But there is a very good discussion in Beattie:2022a as to why it cannot actually be log-normal at all scales
- They show two alternative models that include intermittency
  - compound log-Poisson model
  - Langevin model
- Both give an s-pdf with increasing negative skew as a parameter is increased
  - intermittency for the log-Poisson model
  - density-dependent timescales for Langevin (denser regions evolve faster)
- [ ] I should revisit the notes I made on H II region turbulence for the t-squared project
** TODO Effect of radiation pressure
- The continuum radiation pressure and the line radiation pressure should both be considered
- One thing that we can do is to calculate the radiative force at different points on the simulation and compare with the thermal pressure gradients
  - We can use the single-scattering limit and then correct it with the force multiplier for Lyman alpha
  - However, the H II gas itself is optically thin to the Lyman alpha (which is predominantly concentrated in the wings)
    - The main dynamical effect of the Lyman alpha will be on the expansion of the neutral gas
    - And this is most efficient when the neutral gas fully covers the ionizing source
** Two-dimensional correlation of density and ionization parameter
*** Ionization parameter from the numerical simulations
- Currently, we are simply calculating x^2 / (1 - x), which is proportional to the ionization parameter so long as we have strict photoionization equilibrium
- In theory, we should be calculating it directly from the ionizing flux, but we do not seem to save those files
- We can calculate it using the FORTRAN routines in the cap-post repository
  - 
**** Calculation of neutral column density
This is now done by a new fortran program ~cubecdn.f90~
#+begin_src fish :eval no :dir /Users/will/Work/Garrelt/results-sac
  set d /Users/will/Dropbox/cap-post/src
  for i in (seq 3 30)
      set ii (printf "%02d" $i)
      echo 04052012_4_00$ii | $d/cubecdn
  end
#+end_src
**** Calculation of the "true" ionization parameter
- The tricky thing about this is to take into account the hardening
  - For the time being we will ignore that
*** Distribution of ionization parameter for a constant-density H II region
** TODO Comparison with numerical simulations
:LOGBOOK:
- Note taken on [2026-01-15 Thu 08:25] \\
  Returning to this project in January 2026
- Note taken on [2026-01-15 Thu 08:46] \\
  Found all the simulation cubes
:END:
Use the cubes from the Sac paper
*** Scripts to calculate the pdf
Let's use marimo again for the initial exploration

*** Where to find the simulation cubes

**** TODO Original search for files
- On my laptop:
  - Original Garrelt cubes are now copied from the SSD-2TB to the local disk
    - [[file:../../Work/Garrelt/results-pdr/]]
    - Only one save time apparently (90,000 yrs)
  - Some Sac cubes in [[file:../OrionStats/bigdata/]]
    - We mainly just have emissivities such as [[file:../OrionStats/bigdata/04052012_4_0030e-Halpha.fits]]
    - These are a much later times
- On nil:
  - ~/fs/nil/other0/will/results-sac~ has lots of cubes
  - *But* it is missing the ionization fraction
- On nas11
  - ~/fs/nas11/other0/will/Garrelt/results-sac~
  - This has everything - hurray!
  - 

** Figures for the paper

*** Image showing different density structures in the simulation cubes
- We can use the image ~rgb-NHO-04052012_4-evo-t0003-th135.0-ph135.0-n28-0022.png~
- Have some hilight boxes that point out different structures
  - small globules
  - big globules with striated flows (point out that this is despite being pure HD)
  - cavities formed by said flows
  - extinction due to foreground filaments
  - 

*** Figure showing cut planes through the simulations
- We can show the RGB image of the three emission processes
  - Red :: ionized mechanical dissipation rate
  - Green :: H alpha
  - Blue :: neutral mechanical dissipation rate
- We could even try using better (non primary) colors to make it look less garish
- Also show the radial velocity on the PiYG diverging colormap
- Good cut planes to show:
  1. t=25, order=312 (zx plane), y = 297 (1-based)
     - shows a nice variety of photoevaporation flows of different sizes
  2. t=15, xz, y=262 (0-based)
     - Ditto
